
---
version: 2
updates:
    # Enable Github Action updates
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "(GHA)"
      labels:
          - "dependencies"
          - "patch"
          - "actions"
    
